export const drinks = {
  cappuccino: {
    ingredients: ["espresso", "milk", "foam"],
    decoys: ["syrup", "cinnamon", "honey"],
  },
  americano: {
    ingredients: ["espresso", "water"],
    decoys: ["lemon", "salt", "soda"],
  },
  latte: {
    ingredients: ["espresso", "milk"],
    decoys: ["vanilla", "pepper", "syrup"],
  },
  mocha: {
    ingredients: ["espresso", "milk", "chocolate"],
    decoys: ["butter", "caramel", "jam"],
  },
  black: {
    ingredients: ["coffee", "water"],
    decoys: ["espresso", "milk", "foam"],
  },
  espresso: {
    ingredients: ["espresso"],
    decoys: ["coffee", "milk", "vanilla"],
  },
  frappuccino: {
    ingredients: ["coffee", "ice", "milk"],
    decoys: ["vanilla", "caramel", "foam"],
  },
  macchiato: {
    ingredients: ["espresso", "foam"],
    decoys: ["chocolate", "milk", "ice"],
  },
  flatwhite: {
    ingredients: ["espresso", "steamed milk"],
    decoys: ["foam", "sugar", "cocoa"],
  },
  affogato: {
    ingredients: ["espresso", "ice cream"],
    decoys: ["milk", "whipped cream", "sugar"],
  },
};

export const customerOrders = [
  {
    quote: "Mornings demand a smooth cappuccino with some nice foam.",
    drink: "cappuccino",
  },
  {
    quote: "Give me an americano, I've got a long day ahead.",
    drink: "americano",
  },
  { quote: "A latte sounds so good right now.", drink: "latte" },
  {
    quote: "Chocolate and coffee, please may I have a mocha?",
    drink: "mocha",
  },
  {
    quote: "Feeling exquisite today, give me a flat white.",
    drink: "flatwhite",
  },
  { quote: "Ice cream! Give me an Affogato RIGHT NOW!", drink: "affogato" },
  { quote: "Smooth Operator, lemme get uh... flatwhite", drink: "flatwhite" },
  {
    quote: "Im so tired, I need a boost. One espresso please.",
    drink: "espresso",
  },
  {
    quote: "I'm craving something chill. Frappuccino time!",
    drink: "frappuccino",
  },
  {
    quote: "A macchiato please, I like a little foam on top.",
    drink: "macchiato",
  },
  { quote: "A basic black coffee. Keep it simple.", drink: "black" },

  {quote: "I need something to take the edge off. Coffee black.", drink: "black"},
];

export const wordPool = {
  1: [
    "milk",
    "foam",
    "ice",
    "tea",
    "hot",
    "cup",
    "mug",
    "brew",
    "pour",
    "sugar",
    "cream",
    "sweet",
    "bean",
    "roast",
    "grind",
    "shot",
    "press",
    "latte",
    "java",
    "steep",
    "mix",
    "sip",
    "drink",
    "heat",
    "mild",
    "melt",
    "dark",
    "tall",
    "small",
    "bold",
    "honey",
    "mint",
    "soft",
    "mild",
    "whip",
  ],
  2: [
    "espresso",
    "vanilla",
    "cinnamon",
    "caramel",
    "coffee",
    "frappe",
    "machine",
    "counter",
    "morning",
    "pickup",
    "syrup",
    "grinder",
    "steamer",
    "drizzle",
    "barista",
    "blender",
    "receipt",
    "checkout",
    "flavor",
    "kitchen",
  ],
  3: [
    "quarantine",
    "chocolate",
    "bitterness",
    "ingredient",
    "inventory",
    "temperature",
    "handcrafted",
    "precision",
    "specialist",
    "complexity",
    "equipment",
    "caffeinate",
    "espressoed",
    "management",
    "experiment",
    "concoction",
    "mechanized",
    "stimulation",
    "frequency",
    "sensation",
  ],
  4: [
    "bioluminescence",
    "transcendental",
    "subterranean",
    "institutionalized",
    "refrigeration",
    "metamorphosis",
    "counterculture",
    "unquestionable",
    "disorientation",
    "revolutionary",
    "extraordinary",
    "microprocessor",
    "deconstruction",
    "unpredictable",
    "hypersensitive",
  ],
};
